server:
  port: 22348

spring:
  profiles:
    active: dev
  application:
    name: order-service
  # 以下这一段配置是在 native 打包时用到的，不要删除（备用，因为 native 打包的方案失败了）
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    stream:
      kafka:
        bindings:
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.IntegerSerializer
                value:
                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  subject:
                    name:
                      strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
                schema:
                  registry:
                    url: http://localhost:9092
      bindings:
        replenishStockProducer-out-0:
          destination: replenishStockTopic
        updateMemberPointProducer-out-0:
          destination: updateMemberPointTopic
        replenishBalanceProducer-out-0:
          destination: replenishBalanceTopic

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework: info

seata:
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: 'SEATA_GROUP'
      namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
      dataId: 'seataServer.properties'
      username: 'nacos'
      password: 'nacos'

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:31227/xxl-job-admin
    accessToken: default_token
    executor:
      # 这里的应用名称要跟 xxl-job-admin 任务调度中心 -> 执行器管理 -> 执行器的 AppName 保持一致
      appname: ${spring.application.name}
      address: ""
      ip: ""
      # 0 表示自动获取端口
      port: 0
      logpath: "F:/temp/logs/xxl-job"
      logretentiondays: 30
