server:
  port: 22347

spring:
  profiles:
    active: dev
  application:
    name: member-service
  # 以下这一段配置是在 native 打包时用到的，不要删除（备用，因为 native 打包的方案失败了）
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    function:
      definition: updateMemberPointConsumer;
    stream:
      kafka:
        bindings:
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.IntegerSerializer
                value:
                  serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
                  subject:
                    name:
                      strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
                schema:
                  registry:
                    url: http://localhost:9092
      bindings:
        updateMemberPointConsumer-in-0:
          destination: updateMemberPointTopic

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


seata:
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: 'SEATA_GROUP'
      namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
      dataId: 'seataServer.properties'
      username: 'nacos'
      password: 'nacos'

