spring:
  cloud:
    nacos:
      discovery:
        serverAddr: localhost:8848
        username: 'nacos'
        password: 'nacos'
        namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
      config:
        serverAddr: ${spring.cloud.nacos.discovery.serverAddr}
        username: ${spring.cloud.nacos.discovery.username}
        password: ${spring.cloud.nacos.discovery.password}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - nacos:common.yml?refreshEnabled=true
      - nacos:${spring.application.name}.yml?refreshEnabled=true
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
