server:
  port: 8888

spring:
  application:
    name: gateway
  # 以下这一段配置是在 native 打包时用到的，不要删除（备用，因为 native 打包的方案失败了）
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    sentinel:
      enabled: true
      filter:
        enabled: false
      transport:
        port: 8719
        dashboard: localhost:23896
        client-ip: 127.0.0.1
      # 不要设置成 true ，否则在 sentinel dashboard 看到的菜单会不同
      eager: false
      datasource:
        gw-flow:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-gateway-gw-flow-rule.json
            group-id: SENTINEL_GROUP
            data-type: json
            namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
            username: nacos
            password: nacos
            rule-type: gw-flow
        system:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-gateway-system-rule.json
            group-id: SENTINEL_GROUP
            data-type: json
            namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
            username: nacos
            password: nacos
            rule-type: system
        gw-api-group:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-gateway-gw-api-group-rule.json
            group-id: SENTINEL_GROUP
            data-type: json
            namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
            username: nacos
            password: nacos
            rule-type: gw-api-group

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.gateway: info
    reactivefeign: info
    com.playtika: info
    io: info
