server:
  port: 22345

spring:
  profiles:
    active: dev
  application:
    name: admin-service
  # 以下这一段配置是在 native 打包时用到的，不要删除（备用，因为 native 打包的方案失败了）
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    function:
      definition: replenishStockConsumer;replenishBalanceConsumer
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          replenishStockConsumer-in-0:
            consumer:
              # tag: {@code tag1||tag2||tag3 }; sql: {@code 'color'='blue' AND 'price'>100 } .
              #              subscription: 'TagA || TagC || TagD'
              push:
                orderly: true
          replenishBalanceConsumer-in-0:
            consumer:
              # tag: {@code tag1||tag2||tag3 }; sql: {@code 'color'='blue' AND 'price'>100 } .
              #              subscription: 'TagA || TagC || TagD'
              push:
                orderly: true
      bindings:
        replenishStockConsumer-in-0:
          destination: replenishStockTopic
          group: replenishStockConsumerGroup
        replenishBalanceConsumer-in-0:
          destination: replenishBalanceTopic
          group: replenishBalanceConsumerGroup

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

seata:
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: 'SEATA_GROUP'
      namespace: '5e63d532-6a67-403f-b4b4-6e37a3ab57b1'
      dataId: 'seataServer.properties'
      username: 'nacos'
      password: 'nacos'


